{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "import importtestsmodule\n",
    "import json\n",
    "import kafka_client\n",
    "import utils\n",
    "import test_da\n",
    "import test_jms\n",
    "import pprint\n",
    "\n",
    "config_path = \"../config.json\"\n",
    "cred_twitter_path = \"../twitter.cred\"\n",
    "cred_reddit_path = \"../reddit.cred\"\n",
    "pp=pprint.PrettyPrinter()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Configuration and topics\n",
    "\n",
    "### Config\n",
    "\n",
    "`kafka_server` - set to `localhost:9094` (use `kafka:9092` if you run it inside a container)\n",
    "\n",
    "### Topics\n",
    "\n",
    "`sentiment` - sentiment analyser\n",
    "\n",
    "### Credentials\n",
    "\n",
    "Stored in a file `cred.json`. Some data acquirers require credentials.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pp.pprint(utils.load_config(cred_twitter_path))\n",
    "pp.pprint(utils.load_config(cred_reddit_path))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tests"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Test data acquirer - data acquisition\n",
    "\n",
    "**Prerequisities**:\n",
    "- The data acquirer listents at a topic `config['topics']['dataacquirer_update_topic']`\n",
    "- Credentials in case of a twitter data acquirer or reddit data acquirer.\n",
    "\n",
    "**Steps**\n",
    "\n",
    "- Creates new job\n",
    "- Waits for one message\n",
    "- Checks that the message is in the a correct post\n",
    "  - Success if true, fails otherwise\n",
    "- Stops the running job"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Testing Twitter data acquirer\")\n",
    "test_da.start_test(\"../config.json\",cred_twitter_path)\n",
    "\n",
    "print(\"Testing Reddit data acquirer\")\n",
    "test_da.start_test(\"../config.json\",cred_reddit_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Test job service registration and replay\n",
    "\n",
    "**Prerequisites**:\n",
    "\n",
    "- Jms must run (on `localhost:5100` in debug or `localhost:6009` in docker both defined in `config[uris][jms_submit_uri]`)\n",
    "\n",
    "**Steps**:\n",
    "\n",
    "- Registering new components\n",
    "- Submit job config\n",
    "- Assert received job configs for each component\n",
    "  - Asserting data acquirer job config\n",
    "  - Asserting analyser job config\n",
    "- Assert replayed data acquirer config\n",
    "  - Asserting data acquirer job config\n",
    "  - Asserting analyser job config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "config loaded successfully\n"
     ]
    },
    {
     "ename": "NoBrokersAvailable",
     "evalue": "NoBrokersAvailable",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNoBrokersAvailable\u001b[0m                        Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-11-d268bd93b01e>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mtest_jms\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstart_test\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"../config.json\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\swproj\\socneto\\tests\\code\\test_jms.py\u001b[0m in \u001b[0;36mstart_test\u001b[1;34m(config_path)\u001b[0m\n\u001b[0;32m    143\u001b[0m \u001b[1;32mdef\u001b[0m \u001b[0mstart_test\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconfig_path\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m\"../config.json\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    144\u001b[0m     \u001b[0mconfig\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mutils\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mload_config\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconfig_path\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 145\u001b[1;33m     \u001b[0mkafka\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mkafka_client\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mKafkaClient\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'kafka'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'kafka_server'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    146\u001b[0m     \u001b[0mjms_registration\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconfig\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'topics'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'registration_channel_name'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    147\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\swproj\\socneto\\tests\\code\\kafka_client.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, server_address)\u001b[0m\n\u001b[0;32m      6\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mserver_address\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_server_address\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mserver_address\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 8\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mproducer\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mKafkaProducer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbootstrap_servers\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mserver_address\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      9\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     10\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mproduce_request\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mtopic\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\kafka\\producer\\kafka.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, **configs)\u001b[0m\n\u001b[0;32m    379\u001b[0m         client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',\n\u001b[0;32m    380\u001b[0m                              \u001b[0mwakeup_timeout_ms\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'max_block_ms'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 381\u001b[1;33m                              **self.config)\n\u001b[0m\u001b[0;32m    382\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    383\u001b[0m         \u001b[1;31m# Get auto-discovered version from client if necessary\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\kafka\\client_async.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, **configs)\u001b[0m\n\u001b[0;32m    237\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'api_version'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    238\u001b[0m             \u001b[0mcheck_timeout\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'api_version_auto_timeout_ms'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m/\u001b[0m \u001b[1;36m1000\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 239\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'api_version'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcheck_version\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mcheck_timeout\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    240\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    241\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_can_bootstrap\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\kafka\\client_async.py\u001b[0m in \u001b[0;36mcheck_version\u001b[1;34m(self, node_id, timeout, strict)\u001b[0m\n\u001b[0;32m    890\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    891\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_lock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrelease\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 892\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mErrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mNoBrokersAvailable\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    893\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    894\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mwakeup\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNoBrokersAvailable\u001b[0m: NoBrokersAvailable"
     ]
    }
   ],
   "source": [
    "test_jms.start_test(\"../config.json\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Test analysers\n",
    "\n",
    "**Prerequisites**:\n",
    "\n",
    "n/a\n",
    "\n",
    "**Steps**:\n",
    " \n",
    "TODO"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "client = kafka_client.KafkaClient(\"localhost:9094\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.coordinator.assignors.range:No partition metadata for topic job_management.registration.request\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'ComponentId': 'DataAnalyser_topics', 'ComponentType': 'DATA_ANALYSER', 'UpdateChannelName': 'job_management.job_configuration.DataAnalyser_topics', 'InputChannelName': 'job_management.component_data_input.DataAnalyser_topics', 'attributes': {'outputFormat': {'topics': 'textListValue'}}}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]> timed out after 30000 ms. Closing connection.\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "ERROR:kafka.conn:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv4 ('127.0.0.1', 9094)]>: Error receiving network data closing socket\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jry\\Anaconda3\\lib\\site-packages\\kafka\\conn.py\", line 942, in _recv\n",
      "    data = self._sock.recv(self.config['sock_chunk_bytes'])\n",
      "ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n"
     ]
    }
   ],
   "source": [
    "regpost = client.get_message_from_topic(\"job_management.registration.request\")\n",
    "print(regpost)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:kafka.client:<BrokerConnection node_id=1001 host=localhost:9094 <connected> [IPv6 ('::1', 9094, 0, 0)]> timed out after 30000 ms. Closing connection.\n",
      "WARNING:kafka.client:Node 1001 connection failed -- refreshing metadata\n",
      "WARNING:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='job_management.component_data_input.DataAnalyser_topics', partition=0) with base offset -1 and error KafkaTimeoutError: Batch for TopicPartition(topic='job_management.component_data_input.DataAnalyser_topics', partition=0) containing 1 record(s) expired: 30 seconds have passed since batch creation plus linger time.\n",
      "WARNING:kafka.producer.record_accumulator:Expired 1 batches in accumulator\n"
     ]
    },
    {
     "ename": "KafkaTimeoutError",
     "evalue": "KafkaTimeoutError: Batch for TopicPartition(topic='job_management.component_data_input.DataAnalyser_topics', partition=0) containing 1 record(s) expired: 30 seconds have passed since batch creation plus linger time",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKafkaTimeoutError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-43-06a33e083bf0>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mtopic\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m\"job_management.component_data_input.DataAnalyser_topics\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[0mclient\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mproduce_post\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtopic\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mtext\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"this is totally random text\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mpost\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mclient\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_message_from_topic\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0moutput_topic\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\swproj\\socneto\\tests\\code\\kafka_client.py\u001b[0m in \u001b[0;36mproduce_post\u001b[1;34m(self, topic, originalPostId, postId, jobId, text, originalText, language, source, authorId, dateTime)\u001b[0m\n\u001b[0;32m     89\u001b[0m             \u001b[1;34m\"dateTime\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[0mdateTime\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     90\u001b[0m         }\n\u001b[1;32m---> 91\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mproduce_request\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mtopic\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     92\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     93\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m__del__\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\swproj\\socneto\\tests\\code\\kafka_client.py\u001b[0m in \u001b[0;36mproduce_request\u001b[1;34m(self, request, topic)\u001b[0m\n\u001b[0;32m     12\u001b[0m         \u001b[0mpost_bytes\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mjson_request\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mencode\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'utf-8'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     13\u001b[0m         \u001b[0mfuture\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mproducer\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtopic\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpost_bytes\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 14\u001b[1;33m         \u001b[0mfuture\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m60\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     15\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     16\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mget_message_from_topic\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtopic\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrepeat_times\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m10\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\kafka\\producer\\future.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(self, timeout)\u001b[0m\n\u001b[0;32m     63\u001b[0m         \u001b[1;32massert\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mis_done\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     64\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfailed\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 65\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexception\u001b[0m \u001b[1;31m# pylint: disable-msg=raising-bad-type\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     66\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mvalue\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     67\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKafkaTimeoutError\u001b[0m: KafkaTimeoutError: Batch for TopicPartition(topic='job_management.component_data_input.DataAnalyser_topics', partition=0) containing 1 record(s) expired: 30 seconds have passed since batch creation plus linger time"
     ]
    }
   ],
   "source": [
    "output_topic = \"job_management.component_data_analyzed_input.storage_db\"\n",
    "\n",
    "topic = \"job_management.component_data_input.DataAnalyser_topics\"\n",
    "client.produce_post(topic,text=\"this is totally random text\")\n",
    "\n",
    "post = client.get_message_from_topic(output_topic)\n",
    "print(post)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
